// <auto-generated />
using System;
using CoreAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CoreAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190319091525_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CoreAPI.Models.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.HasKey("AuthorID");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("CoreAPI.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthorID");

                    b.Property<int?>("AuthorID1");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("BookID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("AuthorID1");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("CoreAPI.Models.Book", b =>
                {
                    b.HasOne("CoreAPI.Models.Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoreAPI.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID1");
                });
#pragma warning restore 612, 618
        }
    }
}
